version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_cdc
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"  # Port for consumer
      - "9093:9093"  # Port for producer
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:9093"  # Unique names for each listener
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,PLAINTEXT_DOCKER://localhost:9093"  # Unique listener names
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT"
      KAFKA_LISTENER_NAMES: "PLAINTEXT,PLAINTEXT_DOCKER"  # Unique listener names
      KAFKA_LISTENER_SECURITY_PROTOCOL: "PLAINTEXT"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

